In [1]:
import torch

In [2]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [3]:
x2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [4]:
torch.manual_seed(111)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [5]:
W_query

Parameter containing:
tensor([[0.7156, 0.9140],
        [0.2819, 0.2581],
        [0.6311, 0.6001]])

In [6]:
W_key

Parameter containing:
tensor([[0.9312, 0.2153],
        [0.6033, 0.7328],
        [0.1857, 0.5101]])

In [7]:
W_value

Parameter containing:
tensor([[0.7545, 0.2884],
        [0.5775, 0.0358],
        [0.1026, 0.3419]])

In [11]:
# for 2nd word (journey)
query2 = x2 @ W_query
key2 = x2 @ W_key
value2 = x2 @ W_value

In [12]:
print(query2)
print(key2)
print(value2)

tensor([1.0553, 1.1233])
tensor([1.1596, 1.0926])
tensor([0.9851, 0.4155])


In [14]:
keys = inputs @ W_key
values = inputs @ W_value
queries = inputs @ W_query

print(f"""
keys.shape:{keys.shape}
values.shape:{values.shape}
queries.shape:{queries.shape}
""")


keys.shape:torch.Size([6, 2])
values.shape:torch.Size([6, 2])
queries.shape:torch.Size([6, 2])

