In [1]:
import torch

In [5]:
ip_ids = torch.tensor([0, 2, 4, 3])

In [3]:
vocab_size = 6
output_dim = 3

torch.manual_seed(100)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

embedding_layer.weight

Parameter containing:
tensor([[ 0.1268,  1.3564, -0.0247],
        [-0.8466,  0.0293, -0.5721],
        [-1.2546,  0.0486,  0.2753],
        [-2.1550, -0.7116,  0.0575],
        [ 0.6263, -1.7736, -0.2205],
        [ 2.7467, -1.0480,  1.1239]], requires_grad=True)

In [4]:
embedding_layer(torch.tensor([3]))

tensor([[-2.1550, -0.7116,  0.0575]], grad_fn=<EmbeddingBackward0>)

In [6]:
embedding_layer(ip_ids)

tensor([[ 0.1268,  1.3564, -0.0247],
        [-1.2546,  0.0486,  0.2753],
        [ 0.6263, -1.7736, -0.2205],
        [-2.1550, -0.7116,  0.0575]], grad_fn=<EmbeddingBackward0>)